model:
    arch: frrnB
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 1024
    path: /home/guillermo/Documents/InternshipETS/repos/Semi-supervised-cycleGAN/data/Cityspaces/
training:
    n_workers: 1
    train_iters: 85000
    batch_size: 1
    val_interval: 500
    print_interval: 25
    lr_schedule:
    loss:
        name: 'cross_entropy'
        size_average: False
    optimizer:
        name: 'sgd'
        lr: 1.0e-4
    l_rate: 1.0e-4
    l_schedule:
    momentum: 0.99
    weight_decay: 0.0005
    resume: frrnB_cityscapes_best_model.pkl
    visdom: False
